# 01/08/2017, 42 ms
# Time  : O(m), m being the size of the input, i.e., log(n)
# Space : O(m)
class Solution(object):
    def isHappy(self, n):
        """
        :type n: int
        :rtype: bool
        """

        """
        Examples:
          True : 19 -> 82 -> 68 -> 100 -> 1
          False: 73 -> 58 -> 89 -> 145 -> 42 -> 20 -> 4 -> 16 -> 37 -
                        ^___________________________________________|

        This code is based on the idea to store every n generated by summing
        the square of the digits of the previous n. If a cycle is detected,
        then the number is not happy. Otherwise, it is.
        """
        seen = set()
        while n not in seen:
            seen.add(n)
            n = sum(int(c)**2 for c in str(n))
        return n == 1
